### ISSUE TITLE
 Idx set function is throwing `Error: request entity too large` even on storing 100kb of data. 

### ISSUE THREAD

**Issue by himanshuchawla009** [ceramicnetwork/js-ceramic#1323]
**Describe the bug**
- Idx set function is throwing `Error: request entity too large` even on storing 100kb of data. 

According to [code](https://github.com/ceramicnetwork/js-ceramic/blob/149debbc5320d6343a153067d786e60aa60febe0/packages/core/src/dispatcher.ts#L19) here it is supposed to store 256Kb atleast.

**To Reproduce**

I am using  code snippet given below, in the code snippet below i am able to write this random 100kb data (approx) to  ipfs block using ipfs api but not able to write the same size of data with idx.

```
const ipfs = new ipfsClient({ host: 'localhost', port: '5011', protocol: 'http' });
const idx;

const seed = fromHexString("212aed88de6268912979b74d68e0c65b1234e79a57f0f6c78715c80f41443878");
const provider = new Ed25519Provider(seed)

const connect = async()=>{
  
    await ceramic.setDIDProvider(provider)

    idx = new IDX({ ceramic, aliases })
    
};
const write = async()=>{
    const descDummyData = 'x'.repeat((100 * 1024));
    let  ipfsCid = await ipfs.dag.put({name: descDummyData});

    let stat = await ipfs.block.stat(ipfsCid.toBaseEncodedString())
    console.log("ipfs stat", stat);
    const doc = await idx.set('testTkeyMetaBig', {
        encMetadata: descDummyData.toString(),
    }, 
    { 
        pin: true
    })
}
```

**Expected behavior**
- It should allow me to write data atleast to 256KB and it would be great to know the rationale behind this 256KB limit. 

**Screenshots**
<img width="1440" alt="Screenshot 2021-04-27 at 00 25 20" src="https://user-images.githubusercontent.com/14052374/116135719-108cf580-a6ef-11eb-942e-1fa4e8fb706d.png">

**Machine, OS, browser information (please complete the following information):**
- Macos Big Sur

**Comment by oed** [comment]
The reason the limit exist is to limit the extent users can DoS Ceramic nodes by creating very large records.

The limit might be hit before the data you add is 256kB because the underlying *signed commit* encodes the data as a json-patch and makes a signature over it. Not sure exactly why you are hitting the limit in this case. Might be worth investigating this more.
cc @stbrody

**Comment by stbrody** [comment]
I don't believe this is due to the 256kb commit size limit.  The error message from hitting that limit in Ceramic is of the form "[...]record size exceeds the maximum block size[...]": https://github.com/ceramicnetwork/js-ceramic/blob/149debbc5320d6343a153067d786e60aa60febe0/packages/core/src/dispatcher.ts#L110

Doing a Google search for "request entity too large" turns up results suggesting that this error usually comes from a web server when the HTTP request is too large.  Given that this works for you when using IPFS directly, it's seems most likely that this error is coming from the internal Express.js web server used within the Ceramic daemon.  We might have to do something on our end to make sure Express is configured to allow large enough requests.

**Comment by stbrody** [comment]
I can reproduce this issue. I put up https://github.com/ceramicnetwork/js-ceramic/pull/1324 with the repro

**Comment by stbrody** [comment]
Fix turned out to be easy, updated repro PR to include the fix
