### ISSUE TITLE
Investigate if we can remove loading inner CID from SignedCommits in ConflictResolution.findIndex

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1434]
See https://github.com/ceramicnetwork/js-ceramic/pull/1422 for more context

**Comment by smrz2001** [comment]
From my analysis so far, I think the question to ask is actually:
_How can we remove loading inner CID from SignedCommits in ConflictResolution.findIndex?_

`findIndex` is utility function that doesn't make sense to contain a side-effect as heavy as _**IPFS lookups in a loop**_. Sure enough, because it is a utility function, it's being used in numerous places as such and injecting hidden delays as a result.

I'm looking into removing the additional inner CID lookup and refactoring the calling logic to not need `findIndex` to unwrap signed commits.

@oed @stbrody @ukstv

**Comment by stbrody** [comment]
Have you found any code yet that actually relies on this behavior?  What if you just did the simple change of ripping out the ipfs lookups from _findIndex with no other changes?  Would anything break?

**Comment by smrz2001** [comment]
Was going to try that too after a little more analysis.

From what I can tell, nothing will break because the log is being expanded in other spots and doesn't need `findIndex` to do it. However, in a number of spots it looks like it's adding redundant work without any benefit.

**Comment by smrz2001** [comment]
And my thinking behind that is that whenever the log is mutated (via `fetchLog`?), the inner CIDs are always unwrapped and so it's redundant to do so in `findIndex`.

**Comment by smrz2001** [comment]
> Was going to try that too after a little more analysis. Doesn't look like anything will break.

All tests are passing without the extra lookup and, in fact, brought down the IPFS lookup count from 7 to 6 in the test you'd marked with a TODO @stbrody
