### ISSUE TITLE
Disable ajv 'addUsedSchema" flag when validating schemas

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1526]
The schema validation library we use, `ajv`, caches schemas with the same "id".  This can cause issues if there are multiple unique Ceramic TileDocuments defining schemas that use the same underlying schema.  We can disable that behavior by setting the [addUsedSchema](https://ajv.js.org/options.html#addusedschema) property to false in [Utils.validate()](https://github.com/ceramicnetwork/js-ceramic/blob/d2fab076dd07dcb12a9564b00f86c7fc48afff66/packages/core/src/utils.ts#L50)

**Comment by fmedv** [comment]
Due to this issue it unfortunately reusing schemas that are used to validate several JSON files fails with ```HTTP request to 'http://example.com:7007/api/v0/streams' failed with status 'Internal Server Error': {"error":"schema with key or id \"http://example.com/draft/mydraft/example.schema.json\" already exists"}```. If the "$id" property is not set it seems that schemas that are referencing each other are not able to resolve the references properly. ```HTTP request to 'http://example.com:7007/api/v0/streams' failed with status 'Internal Server Error': {"error":"can't resolve reference http://example.com/draft/mydraft/example.schema.json#/definitions/testDefinition from id #properties/testProperty"}``` 
So if  schema are splitted into several files and referencing each other this seems to be a big issue.

**Comment by stbrody** [comment]
Thanks for the report @fmedv!  We're stretched pretty thin as a team right now, but we'd absolutely welcome PRs for this if you want to try to fix it yourself!
