### ISSUE TITLE
Improve performance of applying tip for pinned streams

### ISSUE THREAD

**Issue by smrz2001** [ceramicnetwork/js-ceramic#1559]
All CIDs in the Stream log are being retrieved again every time a new tip is applied.

`StateManager::_handleTip() => StateManager::_updateStateIfPinned() => PinStore::add() => PinStore::pointsOfInterest()`

```
    protected async pointsOfInterest(state: StreamState): Promise<Array<CID>> {
        const log = state.log as Array<LogEntry>

        const points: CID[] = []
        for (const { cid } of log) {
            points.push(cid)

            const record = await this.retrieve(cid)

```
PinStore::retrieve() maps to this (from pin-store-factory.ts):
```
        const retrieve = async (cid: CID): Promise<any> => {
            const blob = await ipfs.dag.get(cid, { timeout: IPFS_GET_TIMEOUT })
            return blob?.value
        }
```

**Comment by oed** [comment]
Didn't we already have a ticket for this @ukstv ?

**Comment by ukstv** [comment]
No, we did not. I overlooked pinning part. The issue here fully makes sense.

One thing to think about before implementation @smrz2001: please, make sure you have some numbers to demonstrate the effect of the change here. For example,
- _before change_ we have _this_ amount of retrievals which results in _this_ time per `pin.add` operation,
- _after change_ we have _this_ amount of retrievals which results in _this_ time per `pin.add` operation,
- so this particular change brought _N%_ decrease in `pin.add` time.

It can be something low key, like an external script that you run on your machine, nothing fancy here.
