### ISSUE TITLE
Add flag to make controller for TileDocuments immutable

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1612]
New field in genesis commit metadata that causes future commits on the stream to fail if they try to change the controllers array in any way

**Comment by stbrody** [comment]
This will be especially useful for streams that use NFT:DID as their controller as without this the current holder of the NFT could always change the controller of associated streams to be themselves, preventing ownership from following the NFT in the future.

CC @ukstv @michaelsena @oed

**Comment by ukstv** [comment]
Pwease, next time, try to go through the respective epic. We'll have less duplicates :)

Nevertheless, the repo is good one, so closing the other issue in favour of this one. Copying from the duplicate:

A stream can be created with controller set to did:nft. Apparently, one can change the controller of a stream at a later time. This can result in a document being squatted by a malicious actor, who happen to be a part of did:nft controller. We should eliminate that attack vector.

One way to do this is to prohibit changing a controller for an nft-controlled stream. Another, is to add an option to a tile document (similar to deterministic) so that one can set if controller can be changed for a tile at genesis time.

This ticket mainly is to track implementation. It also serves as a reminder, so that we do not forget about the issue when writing a specification.
