### ISSUE TITLE
Make TileDocument 'forbidControllerChanges' true by default

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1945]
allowing controller changes should be opt-in, not opt-out.  Most tiles shouldn't perform controller changes given the risk of the data withholding attack that it exposes, and the degree to which it slows down syncing the stream if it has had many controller changes.  Really only 3id streams should be using this most likely.

**Comment by stbrody** [comment]
Something we should consider doing for Ceramic 2.0/3.0/whenever we do a release with application-code level breaking changes.

Not sure how best to track this though @oed @glcohen

**Comment by glcohen** [comment]
adding to the 2.0 epic for now

**Comment by oed** [comment]
This might be problematic for streams that rely on determinism, e.g. IDX and did-datastore.
Would like @PaulLeCam's input before we make a call here.

**Comment by stbrody** [comment]
Ooph yeah that's a good point about it messing with deterministic streams.  Ugh I hate that we can't make any changes to the metadata included in genesis commits without breaking deterministic lookup for existing streams...

**Comment by PaulLeCam** [comment]
I think it's fine to make this breaking change in Ceramic v2 assuming allowing controller change would result in the same deterministic payload? If so, we can work around it in the DID DataStore by explicitly allowing controller change for now, but otherwise yes that would be completely breaking for existing records.
While we're making breaking changes for v2, what do you think about renaming this flag to `allowControllerChanges` rather than having a "double negative" of `forbidControllerChanges: false`?

**Comment by stbrody** [comment]
> what do you think about renaming this flag to `allowControllerChanges` rather than having a "double negative" of `forbidControllerChanges: false`?

Yeah, I was just thinking about this the other day too.  I regret naming it the way I did.  We can change the user-specific option, but we can't change the way it's recorded in the metadata or we break determinism again.
