### ISSUE TITLE
Ensure records conform to spec

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#367]
Make sure the implementation of Records in js-cermaic conforms to https://github.com/ceramicnetwork/ceramic/blob/master/SPECIFICATION.md

**Comment by stbrody** [comment]
@oed, I could use a hand clarifying this ticket and making it a bit more concrete.  LMK if you want to have a call to talk about it, or if you want to just add some context/clarity directly into this ticket.

**Comment by oed** [comment]
The main thing I wanted to make sure with this is that `data` & `header` used in records, `content` and `metadata` used in docstate.

**Comment by stbrody** [comment]
It looks like the tile doctype correctly uses `data` and `header` in the records: https://github.com/ceramicnetwork/js-ceramic/blob/8a86fb68b5f895f64e79a2585a5f854dd6c42088/packages/doctype-tile/src/tile-doctype.ts#L129

The caip10-link doctype however seems to use `content` instead of `data` in the records: https://github.com/ceramicnetwork/js-ceramic/blob/8a86fb68b5f895f64e79a2585a5f854dd6c42088/packages/doctype-caip10-link/src/caip10-link-doctype.ts#L87
