### ISSUE TITLE
Document pinning (different networks)

### ISSUE THREAD

**Issue by simonovic86** [ceramicnetwork/js-ceramic#662]
Make sure that document pinning data is stored separately for each network.

**Comment by stbrody** [comment]
This should involve storing the data in different directories on the file system, as well as updating the pinning API to always require specifying the ceramic network so that data can be stored and requested from the pinstore independently for each network.

This is to avoid records/documents from accidentally jumping from one network to another.  For example: someone uses a docId on testnet, then restarts their node on mainnet and does an update to the same docId, expecting it to load the current state of that docid from pub/sub before applying the update, but instead the node just gets that document's state from the cache and generates its update against the data from testnet
