### ISSUE TITLE
502 and 504 Gateway Errors

### ISSUE THREAD

**Issue by v-stickykeys** [ceramicnetwork/js-ceramic#690]
Getting this frequently on ceramic-dev.3boxlabs.com. Mostly surfaced from calls to  `/api/v0/documents/<docid>`

e.g.
![Screen Shot 2020-12-21 at 1 18 28 PM](https://user-images.githubusercontent.com/8445610/102827712-15444480-43b1-11eb-93ca-1f5e1b7ca137.png)
## __IPFS pinning__
![Screen Shot 2020-12-21 at 1 12 24 PM](https://user-images.githubusercontent.com/8445610/102827730-1b3a2580-43b1-11eb-8932-3c985f8e75d1.png)

## Dispatcher retrieveRecord
![Screen Shot 2020-12-18 at 10 03 58 AM](https://user-images.githubusercontent.com/8445610/102827758-242af700-43b1-11eb-8f7c-11d2786bbcbc.png)

**Comment by zachferland** [comment]
To get more visibility on these we may need to enable logs on the load balancer for the ipfs api, they should show the actual error that causes a 502 to be returned. Definitely load balancer errors in some form, especially since across different requests. Could be from timeouts, connection drops or maybe issues with the headers we are passing/configured, no sure yet.  They definitely happen when the service is unavailable, and the ipfs node is going down a few times a day it looks like, but that is not the only cause, these are pretty evenly distributed throughout the day it looks like.

**Comment by valmack** [comment]
So these 502s were cleaned up after changing the idle timeout to match the timeouts in idx (see this commit )

But we are seeing 504 timeouts now in ceramic and cas deployments (by way of ceramic).

![Screen Shot 2021-01-14 at 5 10 33 PM](https://user-images.githubusercontent.com/8445610/104655751-2456a380-568c-11eb-9473-84a94ddfa5bb.png)

**Comment by oed** [comment]
@valmack this is addressed now, correct?
