### ISSUE TITLE
Dangerous updates - request: ability to commit doc diffs rather than full doc changes

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#718]
Consider some code like:

```js
async func addKVPairToIDX(k, v) {
  const idx = new IDX({ ... })
  const profile = idx.get('basicProfile')
  const newProfile = await idx.set({...profile, [k]: v})
}

await Promise.all([
   addKVPairToIDX(Math.random(), Math.random()),
   addKVPairToIDX(Math.random(), Math.random()),
   addKVPairToIDX(Math.random(), Math.random())
)]

const newProfile = await idx.get('basicProfile')
```

I would expect to see 3 new random k/v pairs on my basicProfile (i know the actual schemas would block this from happening, consider this a hypothetical).

Instead, I actually only see the changes from the last doc - since the `addKVPairToIDX` is `get`ing the latest doc state, and using that state to form the update, but the latest doc state does not include the latest changes from the other parallel calls.

You might think this is an edge case - but if docs take a while to update, and multiple parties can edit a DID, this could happen quite frequently and cause really bad data loss.

Instead, it would be more helpful to just be able to commit _changes_ I want to make to these docs. Those changes could be applied in any order (don't care about whatever CRDT mechanisms are used behind the scenes). Most information on IDX will probably be unordered anyways?

An alternative could be more reactionary (although this is a less preferred approach) - meaning, if the updates _are_ in fact anchored or pinned (not sure in this case which you would need to persist), but just getting overwritten, then we could make some:

`idx.reconcile` call, which could traverse through past updates and apply any changes that were removed if changes were applied in a very tight time span. This seems wonky and could have bad effects too though, especially with encrypted information or GDPR compliance

**Comment by oed** [comment]
What version of `@ceramicnetwork/doctype-tile` are you using. I think what you are describing here is the expected behavior, so could be a bug.

**Comment by stbrody** [comment]
This is a known issue.  Ceramic document updates are all read-modify-write based right now, which means that concurrent updates can race with each other and cause some of them to fail.  We have some longer term ideas around adding CRDT-based doctypes which would resolve these problems as you mention, but no immediate plans to build that.  For now Ceramic is not well suited to documents that are going to have frequent updates from multiple sources.  For the IDX use case this should usually not be a problem, since there is generally one real-world person who owns a given IDX document and that person will usually only be interacting with a single app at a time that creates modifications to that user's IDX

**Comment by oed** [comment]
Ah, I see you're trying to execute them in parallel here.
