### ISSUE TITLE
Daemon slows down over time while running, can't restart it without losing IDX docs

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#731]
This ticket is related to #717 - since restarting the daemon seems to reset it somehow (i'm assuming it cancels all the polling operations).

After using the daemon for a couple hours, it seems to get dramatically slower. Requests start timing out (although this could be an unrelated issue with `ipfs.dag.get` according to @valmack )

Oddly enough, there are some instances where magical "speed boosts" seem to kick in - where suddenly the daemon is able to resolve the resources much faster again.

**Comment by valmack** [comment]
So far it seems correlated to what we are seeing on infra but will update here when I know more

**Comment by stbrody** [comment]
@Schwartz10 Are your client applications long lived, or is the client destroyed and cleaned up every time you run your tests?  If they are long-lived, what happens if you restart the client when things start slowing down, but leave the daemon running?  I'm wondering if the slowdown could be from the client(s) sending an ever growing number of requests to poll the state of various documents.

**Comment by oed** [comment]
@stbrody polling is disabled by default in the http-client.

**Comment by stbrody** [comment]
> @stbrody polling is disabled by default in the http-client.

ah okay, nevermind then
